# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'PhotoExpresso' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhotoExpresso
pod 'AFNetworking', '~> 3.1'
pod 'JSONKit'
pod 'SVProgressHUD', '~> 2.0'
pod 'PayPal-iOS-SDK'
pod 'FXImageView'

  target 'PhotoExpressoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoExpressoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
